ComboBox - New methods + bullet proofing
htmlstreamofficial/preline pull request #479
Opened 2024-10-10 17:17 UTC by mohsinhijazee

This PR proposes few additions to the ComboBox.

I have tested this with SvelteKit and wrapped the Combox as a Svelte Component with full events and multiple instances of the component on the same page fetching data from difference sources so many copies/instances work seemlessly.

Few fixes/improvements:
 - Constructor does not rely on `window.$hsComboBoxCollection` being initialised. Thus users for bundlers (vite etc) don't have to load all of `preline.js`.
 - Fixed an error about invalid nullish statement
 - Fetching and rendering items is now bit more bullet proof, ensures that the returned response is iterable.

Additions  to the CombBox:
 - `apiSearchQueryTransformer` to allow transforming query before `fetch`. This is required in case some APIs use more advanced filtering DSL such as Google's [AIP-160](https://google.aip.dev/160).
 - `selectedItem()` returns elemnent that was selected
 - `selectedValue()` returns the value.
 - `selectedAttr(attr)` returns the custom attribute.

Few other changes to the package.json (required dependencies added, deprecated type definitions replaced with updated packages), few scripts/watch/commands and generation scripts added.

Don't have full context on design choices so some things might seem absurd and I am here to revise as per your feedback FYI @jahaganiev and @olegpix

2024-10-23 15:43 UTC, olegpix requested changes
@mohsinhijazee Hi!
Thank you for your work! Please read the comments left. Correct the PR according to the comments and push changes.
Best regards!

2024-10-23 15:43 UTC, olegpix commented on pnpm-lock.yaml
Please remove this file from the PR. We don't use PNPM.

2024-10-23 15:43 UTC, olegpix commented on package.json
Please focus on TS files (src/plugins/combobox/*.ts). 
You can create a separate PR in which you will provide your vision of bundling. But again, we do not use PNPM.
Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on index.d.ts
Please focus on TS files (src/plugins/combobox/*.ts). You should not generate output files on your side. Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on preline.d.ts
Please focus on TS files (src/plugins/combobox/*.ts). You should not generate output files on your side. Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on dist/combobox.d.ts
Please focus on TS files (src/plugins/combobox/*.ts). You should not generate output files on your side. Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on dist/index.d.ts
Please focus on TS files (src/plugins/combobox/*.ts). You should not generate output files on your side. Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on dist/preline.d.ts
Please focus on TS files (src/plugins/combobox/*.ts). You should not generate output files on your side. Please remove this file from the PR.

2024-10-23 15:43 UTC, olegpix commented on src/index.ts
We fixed this issue through another PR request from another user. Please remove this file from PR.

2024-10-23 15:43 UTC, olegpix commented on src/plugins/select/index.ts
Please create a separate PR for the select. We will be grateful if you will separate PRs by making them separate for each plugin.

2024-10-23 15:43 UTC, olegpix commented on src/utils/index.ts
Please do not use this as a separate helper. This check can be done with the standard Array method Array.isArray

2024-10-23 15:43 UTC, olegpix commented on src/plugins/combobox/index.ts
> +	isArray,
Please use Array.isArray instead.

2024-10-23 15:43 UTC, olegpix commented on src/plugins/combobox/index.ts
> +		if (!isArray(items)) {
Please use Array.isArray instead.

2024-10-24 16:40 UTC, mohsinhijazee commented on pnpm-lock.yaml
Sure!

2024-10-24 16:41 UTC, mohsinhijazee commented on package.json
I don't have clear idea on bundling, I thought that maybe there's some off line step that only maintainers have or similar. I'll remove them.

2024-10-24 16:42 UTC, mohsinhijazee commented on src/plugins/combobox/index.ts
> +	isArray,
Makes sense. Will do.

2024-10-24 16:43 UTC, mohsinhijazee commented on src/utils/index.ts
Yes, that's kinda pointless. 😄

2024-10-24 17:05 UTC, mohsinhijazee commented
@olegpix Thank you for your feedback! 

I have removed everything that was not relevant (`package.json` scripts, generated `dist/` and other `d.ts` files including the change related to `select` plugin) so I hope it is easier to review now.

Also, about packaging and bundling, I think some scripts or steps should be documented within the `package.json` etc. Not so sure about it. What steps/process do you guys follow for that?

2024-11-04 15:05 UTC, olegpix commented
> @olegpix Thank you for your feedback!
> 
> I have removed everything that was not relevant (`package.json` scripts, generated `dist/` and other `d.ts` files including the change related to `select` plugin) so I hope it is easier to review now.
> 
> Also, about packaging and bundling, I think some scripts or steps should be documented within the `package.json` etc. Not so sure about it. What steps/process do you guys follow for that?

Hi,
The process is quite simple, you need to run 3 tasks from the Preline root (consistently):
1. npm run build
2. npm run build:mjs (optional)
3. npm run generate-dts
That's it.

We'll check and approve your PR after the next update, now we are focused on some other tasks.
Thank you for your work!

2024-12-04 00:11 UTC, jahaganiev commented
Hey @mohsinhijazee - thanks a lot for the PR, we will try to include this PR in v2.7.0 update. Thanks!

2025-02-21 19:53 UTC, mohsinhijazee commented on src/plugins/combobox/index.ts
> +			return eval(query) as QueryTransformer;
Yes, this `eval` is used so that the users of the component can utilise `data-*` attributes to setup the search function (transforming the query before it is sent to the server) without going to write further Javascript (and instantiating a control in pure JS) therefore this does not come from the user input per se, rather from the developer/user of the library and I believe this is a safe use case and can't be exploited because it is not linked to an input control that can be manipulated by the end users to change things around.

Even data attribute though dynamically can be changed, but that change won't trigger the `eval` because combobox would be initialised already.

Other alternative is to drop the ability of being able to supply a search function via `data-*` attributes which would result in a component that is less capable when used in typical HTML only scenarios.

2025-06-04 23:56 UTC, jahaganiev commented
Hey @mohsinhijazee - just wanted to update you that after reviewing the source, we unfortunately can’t move forward with this PR. For future contributions, we’d recommend submitting smaller PRs or opening an issue first to align the feature direction with the team.

Really appreciate your involvement either way - thanks again!

2025-06-04 23:56 UTC, closed without merging